name: Lint

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  py-black:
    name: Python Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  go-fmt:
    name: Go Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: Run go fmt
        run: |
          NON_COMPLIANT_FILES=$(gofmt -s -l $(find . -type f -name '*.go'| grep -v "/.template/"))
          if [ -n "$NON_COMPLIANT_FILES" ]; then
            echo "The following files are not formatted correctly:"
            echo "$NON_COMPLIANT_FILES"
            exit 1
          fi
        